// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbaqtkpwjoxirspmknsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiYXF0a3B3am94aXJzcG1rbnNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0Mzc4MDgsImV4cCI6MjA2ODAxMzgwOH0.o8p4xHGxTIl5I1_0390O92ml4DWFypeRZwZji_vbmDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});